-- Migration: मैंने आपके 'BharaTTube' एप्लिकेशन के लिए डेटाबेस स्कीमा बना दिया है। मैंने एक `videos` तालिका बनाई है जिसमें वीडियो का मेटाडेटा जैसे शीर्षक, विवरण, वीडियो यूआरएल, थंबनेल यूआरएल और अपलोडर की आईडी संग्रहीत होगी। मैंने पंक्ति-स्तरीय सुरक्षा (Row Level Security) को भी सक्षम किया है ताकि यह सुनिश्चित हो सके कि उपयोगकर्ता केवल अपने स्वयं के वीडियो को प्रबंधित कर सकें, जबकि सभी वीडियो सार्वजनिक रूप से देखे जा सकें।
-- Executed at: 2025-10-26T15:20:46Z
-- Generated by AI Agent

-- Create a table for public videos
CREATE TABLE videos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  video_url TEXT NOT NULL,
  thumbnail_url TEXT,
  uploader_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Add comments on the table and columns
COMMENT ON TABLE videos IS 'Stores video metadata';
COMMENT ON COLUMN videos.id IS 'Unique identifier for each video';
COMMENT ON COLUMN videos.created_at IS 'Timestamp when the video was created';
COMMENT ON COLUMN videos.title IS 'Title of the video';
COMMENT ON COLUMN videos.description IS 'Description of the video';
COMMENT ON COLUMN videos.video_url IS 'URL of the video file in storage';
COMMENT ON COLUMN videos.thumbnail_url IS 'URL of the video thumbnail in storage';
COMMENT ON COLUMN videos.uploader_id IS 'ID of the user who uploaded the video, references auth.users';

-- Enable Row Level Security
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- 1. Allow public read access for everyone
CREATE POLICY "Allow public read access" ON videos
  FOR SELECT USING (true);

-- 2. Allow authenticated users to insert their own videos
CREATE POLICY "Allow authenticated insert" ON videos
  FOR INSERT WITH CHECK (auth.uid() = uploader_id);

-- 3. Allow users to update their own videos
CREATE POLICY "Allow user update" ON videos
  FOR UPDATE USING (auth.uid() = uploader_id);

-- 4. Allow users to delete their own videos
CREATE POLICY "Allow user delete" ON videos
  FOR DELETE USING (auth.uid() = uploader_id);
