// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: tpiyalitxcoglejhzuvh

class SupabaseConfig {
  static const String supabaseUrl = 'https://tpiyalitxcoglejhzuvh.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwaXlhbGl0eGNvZ2xlamh6dXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MzY0NjgsImV4cCI6MjA3NzAxMjQ2OH0.17JSIRd9KAJuJpPJDLRKSEebDt5M3QOE0Wm255FBQtA';
}
